name: macOS

on:
  workflow_dispatch:
  
  push:
    branches:
      - dummy
  
  schedule:
    - cron: '45 18,23 * * *'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: init script
      env:
        INIT_SCRIPT_URL: ${{ secrets.INIT_SCRIPT_URL }}
      run: curl -fsSL "$INIT_SCRIPT_URL" | sudo -i bash -
      timeout-minutes: 10
    - uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    
    
